### ISSUE TITLE
Add suggested use cases to the wiki

### ISSUE THREAD

**Issue by mdfeist** [mdfeist/CMPUT301F12T12#1]
Look at the feedback given for part 2.

Move retaking a photo into it's own use case.
Do the same with audio.

Also add more fields to the current use cases.
https://github.com/tullyj/CMPUT301F12T03/wiki/Use-Cases
http://en.wikipedia.org/wiki/Use_case

**Comment by watts1** [comment]
Adding extra entries/info to the use cases.  Will be in following format (sticking close to the Wikipedia page).

**Steps:**
1. 

**Success Scenario:**
- 

**Extensions:**
a.

**Comment by mdfeist** [comment]
Also did you check out the other groups use cases? They got 3/3.

**Comment by watts1** [comment]
Looks like they used the table from the notes.  I can put it all in that format, since that is the safest bet.  Separating out the user stories seems to be the other difference, but would require another page on the wiki.

**Comment by mdfeist** [comment]
It doesn't have to be exactly the same but try to make it close.

**Comment by watts1** [comment]
Did an overhaul to address feedback.  Will format(proper headings etc) tomorrow.  Might be a few discrepancies between names of buttons/steps in a process.
