### ISSUE TITLE
Add buttons in "View Task"

### ISSUE THREAD

**Issue by mdfeist** [mdfeist/CMPUT301F12T12#3]
Add the following buttons.

"Comments", "Photos", "Audio"

**Comment by devonwaldon** [comment]
Did we want buttons? Or did you want to display them as a gallery widget and some list views? I'll look into the gallery widget code, but it may be simpler than adding three more views...

**Comment by mdfeist** [comment]
Ya I updated the view I'm just committing it now.

**Comment by mdfeist** [comment]
Okay, so have a button to add comments but then have a gallery for the images and audio files. Because for comments it will be easer if we have it's own page. Also try and make every thing fit on one page so the user doesn't have to scroll. So no overflow unless necessary.

**Comment by devonwaldon** [comment]
Perfect.
