### ISSUE TITLE
Update the glossary

### ISSUE THREAD

**Issue by mdfeist** [mdfeist/CMPUT301F12T12#7]
Also add it to the Wiki Home page.

**Comment by watts1** [comment]
Added.

**Comment by mdfeist** [comment]
Can you also add terms like Settings, TaskManager and Database. Also things like ListView and ViewGroup.

**Comment by watts1** [comment]
Added a few more things a while ago.  Did not add ListView as that fell under programming terms (see part 2 description).  Not sure what to put for ViewGroup so just left that blank for now.  Will probably add some more later.
